version: '3.7'

services:
  # MySQL 8 service
  # db:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   container_name: mysql-container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456     
  #   volumes:
  #     - data:/var/lib/mysql 
  #   restart: always # Volume para persistir os dados do MySQL

  # init-mysql:
  #   build: .
  #   command: ./init-mysql.sh
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./init-mysql.sh:/init-mysql.sh
  #   restart: "no"

  # Redis service
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379" # Mapeamento da porta do host para a porta do contêiner

  rabbitmq:
    image: rabbitmq:3.12-management #management para poder abrir ele na url ele abre tipo o workbench para podermos configurar filas etc
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin 
  
  # NestJS service
  # nestjs:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile # Caminho para o Dockerfile do NestJS
  #   restart: always
  #   ports:
  #     - "3000:3000" # Mapeamento da porta do host para a porta do contêiner
  #   depends_on:
  #     - db
  #     - redis
  #   env_file:
  #     - .env

volumes:
  data: